name: Build website

on:
  push:
    branches: 
      - v2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.1
    - name: yarn
      run: yarn
    - name: yarn build and export
      run: |
        yarn build
        yarn export
        touch ./out/.nojekyll
        touch ./out/CNAME
        echo 'pmt.nathfreder.dev' > ./out/CNAME
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out
      
