name: Build website

on:
  push:
    branches: 
      - v2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: yarn
      run: yarn
    - name: yarn build and export
      run: |
        yarn build
        yarn export
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'out'      # optional: defaults to entire repository
      
